export const PLACEHOLDER_KEYS = [
  'projectName',
  'projectSlug',
  'goal',
  'userName',
  'assistantName',
  'audience',
  'techStack',
  'externalServices',
  'deadline',
  'today',
  'trackName',
  'experienceLabel',
  'experienceTone',
  'platform',
  'projectStatus',
  'launchTarget',
  'researchPurpose',
  'answerStyle',
  'webAccessLabel',
  'budget',
  'webAccessRule',
  'requirementsList',
  'openQuestions',
  'initialTasks',
  'memoryMap',
  'welcomeTrackLines',
  'trackRules',
  'trackStartHere',
  'toolsStartHere',
  'commandList',
  'sourceTypesList',
  'outputsList',
  'obsidianSection',
  'args',
] as const;

export type PlaceholderKey = (typeof PLACEHOLDER_KEYS)[number];
